### ISSUE TITLE
HMM database

### ISSUE THREAD

**Issue by dyxstat** [koszullab/metaTOR#10]
Hi,

I guess the HMM URL in metator.sh doesn't work. When I run ./metator.sh dependencies, I still cannot download such databases.

Best

**Comment by ABignaud** [comment]
Hi,

I have reupload the hmm database which was missing. It's available at this link: https://github.com/koszullab/metaTOR/raw/master/metator/data/hmm_databases.tgz.

Best,

**Comment by dyxstat** [comment]
Hi,

Thanks for the reply. This problem has been solved. However, I get into trouble again in the final binning step. 

**** Starting binning ****
Drawing enrichment vs. size plots...
Drawing distribution violinplot...
Extracting bin subnetworks and matrices...
INFO :: Loading partition...
INFO :: Loading network...
Extracting bin FASTA files...
WARNING :: /home/Anaconda3/lib/python3.7/site-packages/metator/bin/../scripts/bins.py:216: VisibleDeprecationWarning: Reading unicode strings without specifying the
 encoding argument is deprecated. Set the encoding, use None for the system default.
  zip(*np.genfromtxt(partition_file, usecols=(0, 1), dtype=None))

Traceback (most recent call last):
  File "/home/Anaconda3/lib/python3.7/site-packages/metator/bin/../scripts/bins.py", line 447, in <module>
    main()
  File "/home/Anaconda3/lib/python3.7/site-packages/metator/bin/../scripts/bins.py", line 438, in main
    chunk_size=chunk_size,
  File "/home/Anaconda3/lib/python3.7/site-packages/metator/bin/../scripts/bins.py", line 231, in extract_fasta
    fields = name.split("_")
TypeError: a bytes-like object is required, not 'str'

 Appreciate some suggestions.

Best

**Comment by ABignaud** [comment]
Hi,

Thanks for the report. Indeed, the argument of one function were deprecated, we have corrected the code, so hopefully it should work if you upgrade metator.

Best,
