### ISSUE TITLE
Recursive Louvain Binning

### ISSUE THREAD

**Issue by dyxstat** [koszullab/metaTOR#11]
Hi Developer,

I follow the instructions from your tutorial to do the recursive Louvain clustering as:

'''
metator partition --network-file $subnetwork_dir/contaminated_subnetwork.dat --partition-dir subnetwork_partition_folder
metator binning
'''

However, I find that it will still run 300 times Louvain clustering for each contaminated bin, which consumes a long time and a large space. I change the parameter '--iterations'  in the partition action but it still ran 300 times.

Moreover, I find a round of recursive Louvain binning can already drop the contamination to a low level. So will you run the recursive Louvain binning multiple times?

Thanks!

**Comment by ABignaud** [comment]
Hi,
  
>>>"However, I find that it will still run 300 times Louvain clustering for each contaminated bin, which consumes a long time and a large space. I change the parameter '--iterations' in the partition action but it still ran 300 times."

I will try to see if I can repeat the bug with the 300 iterations with the workflow. We are currently working on a new version of metator which is more user friendly and more efficient which is available in the branch dev of this repository but it's not stable yet but we will release it soon.

>>>"Moreover, I find a round of recursive Louvain binning can already drop the contamination to a low level. So will you run the recursive Louvain binning multiple times?"

Usually we make only one recursive step with 10 iterations of Louvain to decontaminate the bin. But most of the time, one iteration of Louvain algorithm is sufficent to decontaminate the bin.

Thanks for the report,

Amaury
