### ISSUE TITLE
manual_curation_of_metator_MAGs - other binning

### ISSUE THREAD

**Issue by emily-ap** [koszullab/metaTOR#15]
Hello, I'm trying to use anvi'o to help me with manual curation. In your markdown here: https://github.com/koszullab/metaTOR/blob/master/docs/example/manual_curation_of_metator_MAGs.md, it's said you can use your own binning to input. How would I go about getting a binning.txt file myself? Is this a specific part of metaTOR? Thanks for the help!

**Comment by ABignaud** [comment]
Hello, 

When you run the full pipeline of metator,  using `metator pipeline` you should have normally the ˋbinning.txt` file in your output directory. 

This is a ˋtsv` file (columns separated by tabulation) with two columns: the contig name and the name of the bin assigned to the config. It only contains contigs which are binned to reduce the size of the final anvio object. It could be use a an input to import a binning results in anvio.

In the tutorial, I used the binning from metator and therefore I load the binning output from metator in anvio using the file generated by metator. However, if you want to load another binning using another pipeline or if you have modified the metator binning using others information. You can generate a new `binning.txt` file with your new binning and run the anvio analysis using it.

**Comment by emily-ap** [comment]
Great thank you so much! This is what I was thinking it would be. The clarification has helped - I'll close the issue now!
