### ISSUE TITLE
network.py TypeError: Argument must be string or unicode.

### ISSUE THREAD

**Issue by cpadillla1331** [koszullab/metaTOR#3]
Hello, 

I've been trying to implement this tool and cannot get past the first alignment segment. 

If I run $ ./meta3c.sh align -1 fastq_r1 -2 fastq_r2 -a assembly -q 20 -c 10000 -s 10000 -p new_project
after merging bams
I get this error:

Traceback (most recent call last):
  File "/mnt/nas3/cory/home_dir/metaTOR-master/network.py", line 749, in <module>
    parameters=parameters)
  File "/mnt/nas3/cory/home_dir/metaTOR-master/network.py", line 97, in alignment_to_contacts
    with pysam.AlignmentFile(sam_merged, "rb") as alignment_merged_handle:
  File "calignmentfile.pyx", line 302, in pysam.calignmentfile.AlignmentFile.__cinit__ (pysam/calignmentfile.c:4834)
  File "calignmentfile.pyx", line 372, in pysam.calignmentfile.AlignmentFile._open (pysam/calignmentfile.c:5769)
  File "calignmentfile.pyx", line 58, in pysam.calignmentfile._encodeFilename (pysam/calignmentfile.c:3527)
TypeError: Argument must be string or unicode.

Any thoughts? Thanks!

**Comment by baudrly** [comment]
Hello,

in line 667 of network.py, could you try replacing the following:

    parser.add_argument('-i', '--input', type=argparse.FileType('r'),

with:

    parser.add_argument('-i', '--input',

and report back if the error still shows up?

**Comment by cpadillla1331** [comment]
Thanks! Now I’m getting a different error…


File “/home_dir/metaTOR-master/network.py", line 749, in <module>

    parameters=parameters)

  File "/home_dir/metaTOR-master/network.py", line 157, in alignment_to_contacts

    contig_name_forward = read_forward.reference_name

AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'reference_name'

**Comment by baudrly** [comment]
What version of pysam are you using? If not the latest, could you try upgrading it and see if the error still persists?

**Comment by cpadillla1331** [comment]
It looks like I’m using the latest pysam 0.14.1.

**Comment by baudrly** [comment]
I'm having trouble reproducing your error. Apparently it shows up in [earlier versions of pysam](https://github.com/CGATOxford/UMI-tools/issues/199) but should not occur if you're using the latest version. Maybe it's a python2 vs. 3 issue? What's the output of ```pip show pysam``` vs. ```pip3 show pysam```?

**Comment by cpadillla1331** [comment]
They look the same… I found out I don’t have sudo privileges on this machine. I set myself on an AWS instance and got it working like a charm! I’m not exactly sure why that made the difference, but it’s working great. Also just a heads up the link download the moduleHMMs is no longer a valid link.



$ pip show pysam

---

Metadata-Version: 2.0

Name: pysam

Version: 0.14

Summary: pysam

Home-page: https://github.com/pysam-developers/pysam

Author: Andreas Heger

Author-email: andreas.heger@gmail.com

Installer: pip

License: MIT

Location: /usr/local/lib/python3.4/dist-packages

Requires:

Classifiers:

  Development Status :: 4 - Beta

  Intended Audience :: Science/Research

  Intended Audience :: Developers

  License :: OSI Approved

  Programming Language :: Python

  Topic :: Software Development

  Topic :: Scientific/Engineering

  Operating System :: POSIX

  Operating System :: Unix

  Operating System :: MacOS


$ pip3 show pysam

---

Metadata-Version: 2.0

Name: pysam

Version: 0.14

Summary: pysam

Home-page: https://github.com/pysam-developers/pysam

Author: Andreas Heger

Author-email: andreas.heger@gmail.com

Installer: pip

License: MIT

Location: /usr/local/lib/python3.4/dist-packages

Requires:

Classifiers:

  Development Status :: 4 - Beta

  Intended Audience :: Science/Research

  Intended Audience :: Developers

  License :: OSI Approved

  Programming Language :: Python

  Topic :: Software Development

  Topic :: Scientific/Engineering

  Operating System :: POSIX

  Operating System :: Unix

  Operating System :: MacOS

**Comment by baudrly** [comment]
Thanks for the heads up! I fixed the link.

As for the pysam-related error, it is maybe due to the python instance being called by the script not being the same as the one with the updated version of ```pysam```. Not sure how it could happen though.
