### ISSUE TITLE
Failure to produce bin fasta files

### ISSUE THREAD

**Issue by ursky** [koszullab/metaTOR#7]
Dear developers, I got the following error at the very last step of the pipeline:
```
metator binning --n-bins 300
Drawing enrichment vs. size plots...
Drawing distribution violinplot...
Extracting bin subnetworks and matrices...
INFO :: Loading partition...
INFO :: Loading network...
Extracting bin FASTA files...
WARNING :: /home/guritsk1/miniconda2/envs/metator-env/lib/python3.7/site-packages/metator/bin/../scripts/bins.py:216: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  zip(*np.genfromtxt(partition_file, usecols=(0, 1), dtype=None))

Traceback (most recent call last):
  File "/home/guritsk1/miniconda2/envs/metator-env/lib/python3.7/site-packages/metator/bin/../scripts/bins.py", line 448, in <module>
    main()
  File "/home/guritsk1/miniconda2/envs/metator-env/lib/python3.7/site-packages/metator/bin/../scripts/bins.py", line 439, in main
    chunk_size=chunk_size,
  File "/home/guritsk1/miniconda2/envs/metator-env/lib/python3.7/site-packages/metator/bin/../scripts/bins.py", line 231, in extract_fasta
    fields = name.split("_")
TypeError: a bytes-like object is required, not 'str'
```

Could this be a syntax issue, or is this specific to my data? The `chunkname_core_size_300.txt` looks ok:
```
k141_8_0  208074 1
k141_11_0  164531 1
k141_12_0  119734 1
k141_15_0  74519 1
k141_17_0  26 1479
k141_18_0  2 16318
k141_20_0  2 16318
k141_21_0  361 30
k141_24_0  17 2418
k141_25_0  864 16
```

By the way, what do the two columns in `chunkname_core_size_300.txt` represent? Which column is the cluster number? If I know this I can just make a script to split the bin fasta files myself.

**Comment by dyxstat** [comment]
Hi,

I meet the same problem in the binning step. Have you solved this problem?

Best,

**Comment by ursky** [comment]
Nope. It sems the developers just wanted this published and have no intention of actually doing support for this software. Kind of a shame, because it did show promise. Bin3c on the other hand is a breeze to use and also produces great results - I just use that now.

**Comment by rkoszul** [comment]
we had a change of person in charge of the pipeline and it is currently
being updated, the github notifications wasn't updated. Sorry for the
delay! And as you know, there has been a confinement and a bit of hectic
organization in the last few months...as you can see from the other
programs we are usually efficient at tackling issues.
we ll get back to you asap.

**Comment by ABignaud** [comment]
Hi,

Thanks for the report. Indeed, the argument of one function were deprecated, we have corrected the code, so hopefully it should work if you upgrade metator.

Best,
