### ISSUE TITLE
.hmm file existence in the HMM_databases folder 

### ISSUE THREAD

**Issue by martynalukaszewicz** [koszullab/metaTOR#8]
Dear metaTOR Developers,

I hope all is well. We are​ trying to run the metaTOR and we have been running into the HMM databases issue. More specifically the HMM_databases.hmm file seems not to exist:

![image](https://user-images.githubusercontent.com/44623495/85253332-2bca0d00-b41b-11ea-903b-1676147bb6e1.png)

We know that the link to databases in metator.py has been broken as mentioned in issue https://github.com/koszullab/metaTOR/issues/6 therefore we forked metaTOR to our github and updated the link in metator.py like seen in metator.sh:

![image](https://user-images.githubusercontent.com/44623495/85253528-a09d4700-b41b-11ea-9212-d641bfdce3ea.png)

Our current databases folder extracted from metaTOR after updating the link looks like this:

![image](https://user-images.githubusercontent.com/44623495/85253809-30db8c00-b41c-11ea-80d3-2ea5e9fcc977.png)

Should the .hmm file(s) be missing in the HMM_databases folder but built in the process of running metator? We used the command 'metator dependencies' to fetch dependencies. Could this be the issue of the 'hmmer' dependency? Or maybe the issue with how we install the forked metator from our github? HMM_databases folder ended up being in src path instead of lib path so we copied over the databases from src path to a brand new environment that had the original metator from koszullab installed but empty HMM_databased folder ~/metator0513/lib/python3.6/site-packages/metator/bin/HMM_databsases .

**Comment by dyxstat** [comment]
Hi,

I meet similar problems. 

Error: File existence/permissions problem in trying to open HMM file /home/Anaconda3/lib/python3.7/site-packages/metator/bin/HMM_databases/*.hmm.
HMM file /home/Anaconda3/lib/python3.7/site-packages/metator/bin/HMM_databases/*.hmm not found (nor an .h3

Appreciate some suggestions!

**Comment by ABignaud** [comment]
Hi,

I have reupload the hmm database which was missing. It's available at this link: https://github.com/koszullab/metaTOR/raw/master/metator/data/hmm_databases.tgz.

Best,
